# Generated by Django 3.1.1 on 2020-09-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_grosze',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
