# Generated by Django 3.1.1 on 2020-09-13 01:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products_price_grosze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_title', models.CharField(max_length=30)),
                ('price_grosze', models.IntegerField()),
                ('product_container', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('product_ammounts', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('product_prices', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
