# Generated by Django 3.1.1 on 2020-09-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product_ammounts',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_container',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product_prices',
            field=models.JSONField(null=True),
        ),
    ]
